-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2016-04-27 22:29:09 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE TB_ADM_PERMISOSXROL
  (
    NB_ID         NUMBER (10) NOT NULL ,
    NB_IDRECURSO  NUMBER (10) NOT NULL ,
    NB_IDROL      NUMBER (5) NOT NULL ,
    NB_ACTIVO     NUMBER (1) ,
    NB_AGREGAR    NUMBER (1) ,
    NB_ELIMINAR   NUMBER (1) ,
    NB_ACTUALIZAR NUMBER (1)
  ) ;
ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT TB_ADM_PERMISOSXROL_PK PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT TB_ADM_PERMISOSXROL__UN UNIQUE ( NB_IDRECURSO , NB_IDROL ) ;


CREATE TABLE TB_ADM_RECURSO
  (
    NB_ID      NUMBER (10) NOT NULL ,
    VR_NOMBRE  VARCHAR2 (50) ,
    NB_TIPO    NUMBER (1) NOT NULL ,
    NB_IDPADRE NUMBER (10) NOT NULL ,
    VR_URL     VARCHAR2 (250)
  ) ;
COMMENT ON COLUMN TB_ADM_RECURSO.NB_TIPO
IS
  '1-> Principal, 20-> Con hijos' ;
ALTER TABLE TB_ADM_RECURSO ADD CONSTRAINT TB_ADM_RECURSO_PK PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_ADM_RECURSO ADD CONSTRAINT TB_ADM_RECURSO__UN UNIQUE ( VR_NOMBRE , NB_TIPO ) ;


CREATE TABLE TB_ADM_ROL
  (
    NB_ID     NUMBER (5) NOT NULL ,
    VR_NOMBRE VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE TB_ADM_ROL ADD CONSTRAINT TB_ADM_ROL_PK PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_ADM_ROL ADD CONSTRAINT TB_ADM_ROL__UN UNIQUE ( VR_NOMBRE ) ;


CREATE TABLE TB_ADM_USUARIO
  (
    NB_ID        NUMBER (15) NOT NULL ,
    NB_IDPERSONA NUMBER (15) NOT NULL ,
    VR_LOGIN     VARCHAR2 (20) NOT NULL ,
    NB_ACTIVO    NUMBER (1)
  ) ;
ALTER TABLE TB_ADM_USUARIO ADD CONSTRAINT TB_ADM_USUARIO_PK PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_ADM_USUARIO ADD CONSTRAINT TB_ADM_USUARIO__UN UNIQUE ( NB_IDPERSONA ) ;


CREATE TABLE TB_ADM_USUARIOXROL
  (
    NB_ID        NUMBER (10) NOT NULL ,
    NB_IDUSUARIO NUMBER (15) NOT NULL ,
    NB_IDROL     NUMBER (5) NOT NULL
  ) ;
ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT TB_ADM_USUARIOXROL_PK PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT TB_ADM_USUARIOXROL__UN UNIQUE ( NB_IDUSUARIO , NB_IDROL ) ;


CREATE TABLE TB_CURSO
  (
    NB_Id      NUMBER (10) NOT NULL ,
    VR_Codigo  VARCHAR2 (20) NOT NULL ,
    VR_Nombre  VARCHAR2 (100) ,
    NB_IdCurso NUMBER (5)
  ) ;
ALTER TABLE TB_CURSO ADD CONSTRAINT Curso_PK PRIMARY KEY ( NB_Id ) ;


CREATE TABLE TB_DEPENDENCIA_ACADEMICA
  (
    NB_Id     NUMBER (5) NOT NULL ,
    VR_Nombre VARCHAR2 (60 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_DEPENDENCIA_ACADEMICA ADD CONSTRAINT DependenciaAcademica_PK PRIMARY KEY ( NB_Id ) ;


CREATE TABLE TB_DOCENTE
  (
    NB_ID        NUMBER (15) NOT NULL ,
    NB_IdPersona NUMBER (15) NOT NULL
  ) ;
ALTER TABLE TB_DOCENTE ADD CONSTRAINT Docente_PKv2 PRIMARY KEY ( NB_ID ) ;
ALTER TABLE TB_DOCENTE ADD CONSTRAINT Docente__UN UNIQUE ( NB_IdPersona ) ;


CREATE TABLE TB_DOCENTE_SEMESTRE_CURSO
  (
    NB_Id              NUMBER (12) NOT NULL ,
    NB_IdDocente       NUMBER (15) NOT NULL ,
    NB_IdSemestreCurso NUMBER (10) NOT NULL
  ) ;
ALTER TABLE TB_DOCENTE_SEMESTRE_CURSO ADD CONSTRAINT DocenteSemestreCurso_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_DOCENTE_SEMESTRE_CURSO ADD CONSTRAINT DocenteSemestreCurso__UN UNIQUE ( NB_IdDocente , NB_IdSemestreCurso ) ;


CREATE TABLE TB_GRUPO
  (
    NB_Id     NUMBER (7) NOT NULL ,
    VR_Codigo VARCHAR2 (15 BYTE) NOT NULL ,
    VR_Nombre VARCHAR2 (100 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_GRUPO ADD CONSTRAINT Grupo_PK PRIMARY KEY ( NB_Id ) ;


CREATE TABLE TB_PERSONA
  (
    NB_Id                   NUMBER (15) NOT NULL ,
    NB_IdTipoIdentificacion NUMBER (1) NOT NULL ,
    VR_Identificacion       VARCHAR2 (20 BYTE) NOT NULL ,
    VR_Nombres              VARCHAR2 (100 BYTE) NOT NULL ,
    VR_Apellidos            VARCHAR2 (100 BYTE) NOT NULL ,
    VR_Telefono             VARCHAR2 (20 BYTE) ,
    VR_Email                VARCHAR2 (100 BYTE)
  ) ;
ALTER TABLE TB_PERSONA ADD CONSTRAINT PERSONA_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_PERSONA ADD CONSTRAINT Persona__UN UNIQUE ( NB_IdTipoIdentificacion , VR_Identificacion ) ;


CREATE TABLE TB_REPORTE_ACTIVIDAD
  (
    NB_Id                     NUMBER (20) NOT NULL ,
    NB_IdDocenteSemestreCurso NUMBER (12) NOT NULL ,
    NB_IdTipoActividad        NUMBER (5) NOT NULL ,
    DT_Fecha                  DATE NOT NULL ,
    NB_Horas                  NUMBER (4,1) NOT NULL ,
    VR_Descripcion            VARCHAR2 (256 BYTE)
  ) ;
ALTER TABLE TB_REPORTE_ACTIVIDAD ADD CONSTRAINT ReporteActividad_PK PRIMARY KEY ( NB_Id ) ;


CREATE TABLE TB_SEMESTRE
  (
    NB_Id      NUMBER (5) NOT NULL ,
    NB_Anio    NUMBER (4) ,
    NB_Periodo NUMBER (1)
  ) ;
ALTER TABLE TB_SEMESTRE ADD CONSTRAINT Semestre_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_SEMESTRE ADD CONSTRAINT Semestre__UN UNIQUE ( NB_Anio , NB_Periodo ) ;


CREATE TABLE TB_SEMESTRE_CURSO
  (
    NB_Id         NUMBER (10) NOT NULL ,
    NB_IdCurso    NUMBER (10) NOT NULL ,
    NB_IdGrupo    NUMBER (7) NOT NULL ,
    NB_IdSemestre NUMBER (5) NOT NULL
  ) ;
ALTER TABLE TB_SEMESTRE_CURSO ADD CONSTRAINT SemestreCurso_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_SEMESTRE_CURSO ADD CONSTRAINT SemestreCurso__UN UNIQUE ( NB_IdCurso , NB_IdGrupo , NB_IdSemestre ) ;


CREATE TABLE TB_TIPO_ACTIVIDAD
  (
    NB_Id          NUMBER (5) NOT NULL ,
    VR_Nombre      VARCHAR2 (30 BYTE) NOT NULL ,
    VR_Descripcion VARCHAR2 (150 BYTE)
  ) ;
ALTER TABLE TB_TIPO_ACTIVIDAD ADD CONSTRAINT TipoActividad_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_TIPO_ACTIVIDAD ADD CONSTRAINT TipoActividad__UN UNIQUE ( VR_Nombre ) ;


CREATE TABLE TB_TIPO_IDENTIFICACION
  (
    NB_Id          NUMBER (1) NOT NULL ,
    VR_Descripcion VARCHAR2 (30 BYTE) NOT NULL
  ) ;
ALTER TABLE TB_TIPO_IDENTIFICACION ADD CONSTRAINT TipoIdentificacion_PK PRIMARY KEY ( NB_Id ) ;
ALTER TABLE TB_TIPO_IDENTIFICACION ADD CONSTRAINT TipoIdentificacion__UN UNIQUE ( VR_Descripcion ) ;


ALTER TABLE TB_CURSO ADD CONSTRAINT Curso_Curso_FK FOREIGN KEY ( NB_IdCurso ) REFERENCES TB_DEPENDENCIA_ACADEMICA ( NB_Id ) ;

ALTER TABLE TB_DOCENTE_SEMESTRE_CURSO ADD CONSTRAINT DocSemCurso_Docente_FK FOREIGN KEY ( NB_IdDocente ) REFERENCES TB_DOCENTE ( NB_ID ) ;

ALTER TABLE TB_DOCENTE_SEMESTRE_CURSO ADD CONSTRAINT DocSemCurso_SemCur_FK FOREIGN KEY ( NB_IdSemestreCurso ) REFERENCES TB_SEMESTRE_CURSO ( NB_Id ) ;

ALTER TABLE TB_DOCENTE ADD CONSTRAINT Docente_Persona_FK FOREIGN KEY ( NB_IdPersona ) REFERENCES TB_PERSONA ( NB_Id ) ;

ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT PERMISOSXROL_RECURSO_FK FOREIGN KEY ( NB_IDRECURSO ) REFERENCES TB_ADM_RECURSO ( NB_ID ) ;

ALTER TABLE TB_ADM_PERMISOSXROL ADD CONSTRAINT PERMISOSXROL_ROL_FK FOREIGN KEY ( NB_IDROL ) REFERENCES TB_ADM_ROL ( NB_ID ) ;

ALTER TABLE TB_PERSONA ADD CONSTRAINT Persona_TipoIdentificacion_FK FOREIGN KEY ( NB_IdTipoIdentificacion ) REFERENCES TB_TIPO_IDENTIFICACION ( NB_Id ) ON
DELETE CASCADE ;

ALTER TABLE TB_ADM_RECURSO ADD CONSTRAINT RECURSO_RECURSO_FK FOREIGN KEY ( NB_IDPADRE ) REFERENCES TB_ADM_RECURSO ( NB_ID ) ;

ALTER TABLE TB_REPORTE_ACTIVIDAD ADD CONSTRAINT RepAct_DocSemCurso_FK FOREIGN KEY ( NB_IdDocenteSemestreCurso ) REFERENCES TB_DOCENTE_SEMESTRE_CURSO ( NB_Id ) ;

ALTER TABLE TB_REPORTE_ACTIVIDAD ADD CONSTRAINT RepAct_TipoActividad_FK FOREIGN KEY ( NB_IdTipoActividad ) REFERENCES TB_TIPO_ACTIVIDAD ( NB_Id ) ;

ALTER TABLE TB_SEMESTRE_CURSO ADD CONSTRAINT SemestreCurso_Curso_FK FOREIGN KEY ( NB_IdCurso ) REFERENCES TB_CURSO ( NB_Id ) ;

ALTER TABLE TB_SEMESTRE_CURSO ADD CONSTRAINT SemestreCurso_Grupo_FK FOREIGN KEY ( NB_IdGrupo ) REFERENCES TB_GRUPO ( NB_Id ) ;

ALTER TABLE TB_SEMESTRE_CURSO ADD CONSTRAINT SemestreCurso_Semestre_FK FOREIGN KEY ( NB_IdSemestre ) REFERENCES TB_SEMESTRE ( NB_Id ) ;

ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT USUARIOXROL_ROL_FK FOREIGN KEY ( NB_IDROL ) REFERENCES TB_ADM_ROL ( NB_ID ) ;

ALTER TABLE TB_ADM_USUARIOXROL ADD CONSTRAINT USUARIOXROL_USUARIO_FK FOREIGN KEY ( NB_IDUSUARIO ) REFERENCES TB_ADM_USUARIO ( NB_ID ) ;

ALTER TABLE TB_ADM_USUARIO ADD CONSTRAINT USUARIO_PERSONA_FK FOREIGN KEY ( NB_IDPERSONA ) REFERENCES TB_PERSONA ( NB_Id ) ;


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             0
-- ALTER TABLE                             44
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
