package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

/**
 * TbAdmUsuarioxrol generated by hbm2java
 */
public class TbAdmUsuarioxrol implements java.io.Serializable {

	private long nbId;
	private TbAdmUsuario tbAdmUsuario;
	private TbAdmRol tbAdmRol;

	public TbAdmUsuarioxrol() {
	}

	public TbAdmUsuarioxrol(long nbId, TbAdmUsuario tbAdmUsuario, TbAdmRol tbAdmRol) {
		this.nbId = nbId;
		this.tbAdmUsuario = tbAdmUsuario;
		this.tbAdmRol = tbAdmRol;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbAdmUsuario getTbAdmUsuario() {
		return this.tbAdmUsuario;
	}

	public void setTbAdmUsuario(TbAdmUsuario tbAdmUsuario) {
		this.tbAdmUsuario = tbAdmUsuario;
	}

	public TbAdmRol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(TbAdmRol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

}
