package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

/**
 * TbAdmPermisosxrol generated by hbm2java
 */
public class TbAdmPermisosxrol implements java.io.Serializable {

	private long nbId;
	private TbAdmRecurso tbAdmRecurso;
	private TbAdmRol tbAdmRol;
	private Byte nbActivo;
	private Byte nbAgregar;
	private Byte nbEliminar;
	private Byte nbActualizar;

	public TbAdmPermisosxrol() {
	}

	public TbAdmPermisosxrol(long nbId, TbAdmRecurso tbAdmRecurso, TbAdmRol tbAdmRol) {
		this.nbId = nbId;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
	}

	public TbAdmPermisosxrol(long nbId, TbAdmRecurso tbAdmRecurso, TbAdmRol tbAdmRol, Byte nbActivo, Byte nbAgregar,
			Byte nbEliminar, Byte nbActualizar) {
		this.nbId = nbId;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
		this.nbActivo = nbActivo;
		this.nbAgregar = nbAgregar;
		this.nbEliminar = nbEliminar;
		this.nbActualizar = nbActualizar;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbAdmRecurso getTbAdmRecurso() {
		return this.tbAdmRecurso;
	}

	public void setTbAdmRecurso(TbAdmRecurso tbAdmRecurso) {
		this.tbAdmRecurso = tbAdmRecurso;
	}

	public TbAdmRol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(TbAdmRol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

	public Byte getNbActivo() {
		return this.nbActivo;
	}

	public void setNbActivo(Byte nbActivo) {
		this.nbActivo = nbActivo;
	}

	public Byte getNbAgregar() {
		return this.nbAgregar;
	}

	public void setNbAgregar(Byte nbAgregar) {
		this.nbAgregar = nbAgregar;
	}

	public Byte getNbEliminar() {
		return this.nbEliminar;
	}

	public void setNbEliminar(Byte nbEliminar) {
		this.nbEliminar = nbEliminar;
	}

	public Byte getNbActualizar() {
		return this.nbActualizar;
	}

	public void setNbActualizar(Byte nbActualizar) {
		this.nbActualizar = nbActualizar;
	}

}
