package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmRol generated by hbm2java
 */
public class TbAdmRol implements java.io.Serializable {

	private int nbId;
	private String vrNombre;
	private Set tbAdmUsuarioxrols = new HashSet(0);
	private Set tbAdmPermisosxrols = new HashSet(0);

	public TbAdmRol() {
	}

	public TbAdmRol(int nbId, String vrNombre) {
		this.nbId = nbId;
		this.vrNombre = vrNombre;
	}

	public TbAdmRol(int nbId, String vrNombre, Set tbAdmUsuarioxrols, Set tbAdmPermisosxrols) {
		this.nbId = nbId;
		this.vrNombre = vrNombre;
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public Set getTbAdmUsuarioxrols() {
		return this.tbAdmUsuarioxrols;
	}

	public void setTbAdmUsuarioxrols(Set tbAdmUsuarioxrols) {
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

	public Set getTbAdmPermisosxrols() {
		return this.tbAdmPermisosxrols;
	}

	public void setTbAdmPermisosxrols(Set tbAdmPermisosxrols) {
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

}
