package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

/**
 * TbAdmPermisosxrol generated by hbm2java
 */
public class TbAdmPermisosxrol implements java.io.Serializable {

	private long nbId;
	private TbAdmRecurso tbAdmRecurso;
	private TbAdmRol tbAdmRol;
	private Boolean nbActivo;
	private Boolean nbAgregar;
	private Boolean nbEliminar;
	private Boolean nbActualizar;

	public TbAdmPermisosxrol() {
	}

	public TbAdmPermisosxrol(long nbId, TbAdmRecurso tbAdmRecurso, TbAdmRol tbAdmRol) {
		this.nbId = nbId;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
	}

	public TbAdmPermisosxrol(long nbId, TbAdmRecurso tbAdmRecurso, TbAdmRol tbAdmRol, Boolean nbActivo,
			Boolean nbAgregar, Boolean nbEliminar, Boolean nbActualizar) {
		this.nbId = nbId;
		this.tbAdmRecurso = tbAdmRecurso;
		this.tbAdmRol = tbAdmRol;
		this.nbActivo = nbActivo;
		this.nbAgregar = nbAgregar;
		this.nbEliminar = nbEliminar;
		this.nbActualizar = nbActualizar;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbAdmRecurso getTbAdmRecurso() {
		return this.tbAdmRecurso;
	}

	public void setTbAdmRecurso(TbAdmRecurso tbAdmRecurso) {
		this.tbAdmRecurso = tbAdmRecurso;
	}

	public TbAdmRol getTbAdmRol() {
		return this.tbAdmRol;
	}

	public void setTbAdmRol(TbAdmRol tbAdmRol) {
		this.tbAdmRol = tbAdmRol;
	}

	public Boolean getNbActivo() {
		return this.nbActivo;
	}

	public void setNbActivo(Boolean nbActivo) {
		this.nbActivo = nbActivo;
	}

	public Boolean getNbAgregar() {
		return this.nbAgregar;
	}

	public void setNbAgregar(Boolean nbAgregar) {
		this.nbAgregar = nbAgregar;
	}

	public Boolean getNbEliminar() {
		return this.nbEliminar;
	}

	public void setNbEliminar(Boolean nbEliminar) {
		this.nbEliminar = nbEliminar;
	}

	public Boolean getNbActualizar() {
		return this.nbActualizar;
	}

	public void setNbActualizar(Boolean nbActualizar) {
		this.nbActualizar = nbActualizar;
	}

}
