package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbCurso generated by hbm2java
 */
public class TbCurso implements java.io.Serializable {

	private long nbId;
	private TbDependenciaAcademica tbDependenciaAcademica;
	private String vrCodigo;
	private String vrNombre;
	private Set tbSemestreCursos = new HashSet(0);

	public TbCurso() {
	}

	public TbCurso(long nbId, String vrCodigo) {
		this.nbId = nbId;
		this.vrCodigo = vrCodigo;
	}

	public TbCurso(long nbId, TbDependenciaAcademica tbDependenciaAcademica, String vrCodigo, String vrNombre,
			Set tbSemestreCursos) {
		this.nbId = nbId;
		this.tbDependenciaAcademica = tbDependenciaAcademica;
		this.vrCodigo = vrCodigo;
		this.vrNombre = vrNombre;
		this.tbSemestreCursos = tbSemestreCursos;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbDependenciaAcademica getTbDependenciaAcademica() {
		return this.tbDependenciaAcademica;
	}

	public void setTbDependenciaAcademica(TbDependenciaAcademica tbDependenciaAcademica) {
		this.tbDependenciaAcademica = tbDependenciaAcademica;
	}

	public String getVrCodigo() {
		return this.vrCodigo;
	}

	public void setVrCodigo(String vrCodigo) {
		this.vrCodigo = vrCodigo;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	public Set getTbSemestreCursos() {
		return this.tbSemestreCursos;
	}

	public void setTbSemestreCursos(Set tbSemestreCursos) {
		this.tbSemestreCursos = tbSemestreCursos;
	}

}
