package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TbDocente generated by hbm2java
 */
public class TbDocente implements java.io.Serializable {

	private long nbId;
	private TbPersona tbPersona;
//	@JsonManagedReference
	private Set tbDocenteSemestreCursos = new HashSet(0);

	public TbDocente() {
	}

	public TbDocente(long nbId, TbPersona tbPersona) {
		this.nbId = nbId;
		this.tbPersona = tbPersona;
	}

	public TbDocente(long nbId, TbPersona tbPersona, Set tbDocenteSemestreCursos) {
		this.nbId = nbId;
		this.tbPersona = tbPersona;
		this.tbDocenteSemestreCursos = tbDocenteSemestreCursos;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbPersona getTbPersona() {
		return this.tbPersona;
	}

	public void setTbPersona(TbPersona tbPersona) {
		this.tbPersona = tbPersona;
	}

	@JsonIgnore
	public Set getTbDocenteSemestreCursos() {
		return this.tbDocenteSemestreCursos;
	}

	public void setTbDocenteSemestreCursos(Set tbDocenteSemestreCursos) {
		this.tbDocenteSemestreCursos = tbDocenteSemestreCursos;
	}

}
