package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TbDocenteSemestreCurso generated by hbm2java
 */
public class TbDocenteSemestreCurso implements java.io.Serializable {

	private long nbId;
//	@JsonBackReference
	private TbDocente tbDocente;
//	@JsonBackReference
	private TbSemestreCurso tbSemestreCurso;
	
	@JsonBackReference
	private Set tbReporteActividads = new HashSet(0);

	public TbDocenteSemestreCurso() {
	}

	public TbDocenteSemestreCurso(long nbId, TbDocente tbDocente, TbSemestreCurso tbSemestreCurso) {
		this.nbId = nbId;
		this.tbDocente = tbDocente;
		this.tbSemestreCurso = tbSemestreCurso;
	}

	public TbDocenteSemestreCurso(long nbId, TbDocente tbDocente, TbSemestreCurso tbSemestreCurso,
			Set tbReporteActividads) {
		this.nbId = nbId;
		this.tbDocente = tbDocente;
		this.tbSemestreCurso = tbSemestreCurso;
		this.tbReporteActividads = tbReporteActividads;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbDocente getTbDocente() {
		return this.tbDocente;
	}

	public void setTbDocente(TbDocente tbDocente) {
		this.tbDocente = tbDocente;
	}

	public TbSemestreCurso getTbSemestreCurso() {
		return this.tbSemestreCurso;
	}

	public void setTbSemestreCurso(TbSemestreCurso tbSemestreCurso) {
		this.tbSemestreCurso = tbSemestreCurso;
	}

	public Set getTbReporteActividads() {
		return this.tbReporteActividads;
	}

	public void setTbReporteActividads(Set tbReporteActividads) {
		this.tbReporteActividads = tbReporteActividads;
	}

}
