package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TbGrupo generated by hbm2java
 */
public class TbGrupo implements java.io.Serializable {

	private int nbId;
	private String vrCodigo;
	private String vrNombre;
	private Set tbSemestreCursos = new HashSet(0);

	public TbGrupo() {
	}

	public TbGrupo(int nbId, String vrCodigo, String vrNombre) {
		this.nbId = nbId;
		this.vrCodigo = vrCodigo;
		this.vrNombre = vrNombre;
	}

	public TbGrupo(int nbId, String vrCodigo, String vrNombre, Set tbSemestreCursos) {
		this.nbId = nbId;
		this.vrCodigo = vrCodigo;
		this.vrNombre = vrNombre;
		this.tbSemestreCursos = tbSemestreCursos;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public String getVrCodigo() {
		return this.vrCodigo;
	}

	public void setVrCodigo(String vrCodigo) {
		this.vrCodigo = vrCodigo;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

	@JsonIgnore
	public Set getTbSemestreCursos() {
		return this.tbSemestreCursos;
	}

	public void setTbSemestreCursos(Set tbSemestreCursos) {
		this.tbSemestreCursos = tbSemestreCursos;
	}

}
