package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbPersona generated by hbm2java
 */
public class TbPersona implements java.io.Serializable {

	private long nbId;
	private TbTipoIdentificacion tbTipoIdentificacion;
	private String vrIdentificacion;
	private String vrNombres;
	private String vrApellidos;
	private String vrTelefono;
	private String vrEmail;
	private Set tbDocentes = new HashSet(0);
	private Set tbAdmUsuarios = new HashSet(0);

	public TbPersona() {
	}

	public TbPersona(long nbId, TbTipoIdentificacion tbTipoIdentificacion, String vrIdentificacion, String vrNombres,
			String vrApellidos) {
		this.nbId = nbId;
		this.tbTipoIdentificacion = tbTipoIdentificacion;
		this.vrIdentificacion = vrIdentificacion;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
	}

	public TbPersona(long nbId, TbTipoIdentificacion tbTipoIdentificacion, String vrIdentificacion, String vrNombres,
			String vrApellidos, String vrTelefono, String vrEmail, Set tbDocentes, Set tbAdmUsuarios) {
		this.nbId = nbId;
		this.tbTipoIdentificacion = tbTipoIdentificacion;
		this.vrIdentificacion = vrIdentificacion;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
		this.vrTelefono = vrTelefono;
		this.vrEmail = vrEmail;
		this.tbDocentes = tbDocentes;
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbTipoIdentificacion getTbTipoIdentificacion() {
		return this.tbTipoIdentificacion;
	}

	public void setTbTipoIdentificacion(TbTipoIdentificacion tbTipoIdentificacion) {
		this.tbTipoIdentificacion = tbTipoIdentificacion;
	}

	public String getVrIdentificacion() {
		return this.vrIdentificacion;
	}

	public void setVrIdentificacion(String vrIdentificacion) {
		this.vrIdentificacion = vrIdentificacion;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrApellidos() {
		return this.vrApellidos;
	}

	public void setVrApellidos(String vrApellidos) {
		this.vrApellidos = vrApellidos;
	}

	public String getVrTelefono() {
		return this.vrTelefono;
	}

	public void setVrTelefono(String vrTelefono) {
		this.vrTelefono = vrTelefono;
	}

	public String getVrEmail() {
		return this.vrEmail;
	}

	public void setVrEmail(String vrEmail) {
		this.vrEmail = vrEmail;
	}

	public Set getTbDocentes() {
		return this.tbDocentes;
	}

	public void setTbDocentes(Set tbDocentes) {
		this.tbDocentes = tbDocentes;
	}

	public Set getTbAdmUsuarios() {
		return this.tbAdmUsuarios;
	}

	public void setTbAdmUsuarios(Set tbAdmUsuarios) {
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

}
