package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TbSemestreCurso generated by hbm2java
 */
public class TbSemestreCurso implements java.io.Serializable {

	private long nbId;
	private TbCurso tbCurso;
	private TbGrupo tbGrupo;
	private TbSemestre tbSemestre;
	private Set tbDocenteSemestreCursos = new HashSet(0);

	public TbSemestreCurso() {
	}

	public TbSemestreCurso(long nbId, TbCurso tbCurso, TbGrupo tbGrupo, TbSemestre tbSemestre) {
		this.nbId = nbId;
		this.tbCurso = tbCurso;
		this.tbGrupo = tbGrupo;
		this.tbSemestre = tbSemestre;
	}

	public TbSemestreCurso(long nbId, TbCurso tbCurso, TbGrupo tbGrupo, TbSemestre tbSemestre,
			Set tbDocenteSemestreCursos) {
		this.nbId = nbId;
		this.tbCurso = tbCurso;
		this.tbGrupo = tbGrupo;
		this.tbSemestre = tbSemestre;
		this.tbDocenteSemestreCursos = tbDocenteSemestreCursos;
	}

	public long getNbId() {
		return this.nbId;
	}

	public void setNbId(long nbId) {
		this.nbId = nbId;
	}

	public TbCurso getTbCurso() {
		return this.tbCurso;
	}

	public void setTbCurso(TbCurso tbCurso) {
		this.tbCurso = tbCurso;
	}

	public TbGrupo getTbGrupo() {
		return this.tbGrupo;
	}

	public void setTbGrupo(TbGrupo tbGrupo) {
		this.tbGrupo = tbGrupo;
	}

	public TbSemestre getTbSemestre() {
		return this.tbSemestre;
	}

	public void setTbSemestre(TbSemestre tbSemestre) {
		this.tbSemestre = tbSemestre;
	}
	
	@JsonIgnore
	public Set getTbDocenteSemestreCursos() {
		return this.tbDocenteSemestreCursos;
	}

	public void setTbDocenteSemestreCursos(Set tbDocenteSemestreCursos) {
		this.tbDocenteSemestreCursos = tbDocenteSemestreCursos;
	}

}
