package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbSemestre generated by hbm2java
 */
public class TbSemestre implements java.io.Serializable {

	private int nbId;
	private Short nbAnio;
	private Boolean nbPeriodo;
	private Set tbSemestreCursos = new HashSet(0);

	public TbSemestre() {
	}

	public TbSemestre(int nbId) {
		this.nbId = nbId;
	}

	public TbSemestre(int nbId, Short nbAnio, Boolean nbPeriodo, Set tbSemestreCursos) {
		this.nbId = nbId;
		this.nbAnio = nbAnio;
		this.nbPeriodo = nbPeriodo;
		this.tbSemestreCursos = tbSemestreCursos;
	}

	public int getNbId() {
		return this.nbId;
	}

	public void setNbId(int nbId) {
		this.nbId = nbId;
	}

	public Short getNbAnio() {
		return this.nbAnio;
	}

	public void setNbAnio(Short nbAnio) {
		this.nbAnio = nbAnio;
	}

	public Boolean getNbPeriodo() {
		return this.nbPeriodo;
	}

	public void setNbPeriodo(Boolean nbPeriodo) {
		this.nbPeriodo = nbPeriodo;
	}

	public Set getTbSemestreCursos() {
		return this.tbSemestreCursos;
	}

	public void setTbSemestreCursos(Set tbSemestreCursos) {
		this.tbSemestreCursos = tbSemestreCursos;
	}

}
