package com.udea.dominio.dto;
// Generated 28/04/2016 10:30:44 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoIdentificacion generated by hbm2java
 */
public class TbTipoIdentificacion implements java.io.Serializable {

	private short nbId;
	private String vrDescripcion;
	private Set tbPersonas = new HashSet(0);

	public TbTipoIdentificacion() {
	}

	public TbTipoIdentificacion(short nbId, String vrDescripcion) {
		this.nbId = nbId;
		this.vrDescripcion = vrDescripcion;
	}

	public TbTipoIdentificacion(short nbId, String vrDescripcion, Set tbPersonas) {
		this.nbId = nbId;
		this.vrDescripcion = vrDescripcion;
		this.tbPersonas = tbPersonas;
	}

	public short getNbId() {
		return this.nbId;
	}

	public void setNbId(short nbId) {
		this.nbId = nbId;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Set getTbPersonas() {
		return this.tbPersonas;
	}

	public void setTbPersonas(Set tbPersonas) {
		this.tbPersonas = tbPersonas;
	}

}
