package com.udea.dominio.dto;
// Generated 14/05/2016 12:06:50 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TbTipoIdentificacion generated by hbm2java
 */
public class TbTipoIdentificacion implements java.io.Serializable {

	private short nbId;
	private String vrDescripcion;
	@JsonManagedReference
	private Set tbPersonas = new HashSet(0);

	public TbTipoIdentificacion() {
	}

	public TbTipoIdentificacion(short nbId, String vrDescripcion) {
		this.nbId = nbId;
		this.vrDescripcion = vrDescripcion;
	}

	public TbTipoIdentificacion(short nbId, String vrDescripcion, Set tbPersonas) {
		this.nbId = nbId;
		this.vrDescripcion = vrDescripcion;
		this.tbPersonas = tbPersonas;
	}

	public short getNbId() {
		return this.nbId;
	}

	public void setNbId(short nbId) {
		this.nbId = nbId;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	
	public Set getTbPersonas() {
		return this.tbPersonas;
	}

	public void setTbPersonas(Set tbPersonas) {
		this.tbPersonas = tbPersonas;
	}

}
